### ISSUE TITLE
app.bitgo-test.com has WASM issues

### ISSUE THREAD

**Issue by kaminskypavel** [BitGo/BitGoJS#1023]
Hi Team, 
as part of Hedera21 hackathon, I've been playing around with the platform  and couldn't create an THBAR wallet 
seems like WASM is having issues compiling.

I've been redirected here by the hedera team

here's the gist of it

_polyfills.284a93d813815bf81e62.js:2 Unhandled Promise rejection: abort(CompileError: **WebAssembly.instantiate(): Wasm code generation disallowed by embedder**). Build with -s ASSERTIONS=1 for more info. ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:414083)
    at https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:415659
    at e.invoke (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:8955)
    at t.run (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4051)
    at https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:16035
    at e.invokeTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:9639)
    at t.runTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4714)
    at _ (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:11979) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info._

**full log**
```
Some messages have been moved to the Issues panel.
scripts.5c00cd0492a22fbce657.js:459 JQMIGRATE: Migrate is installed, version 3.0.1
scripts.5c00cd0492a22fbce657.js:188 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
(anonymous) @ scripts.5c00cd0492a22fbce657.js:188
scripts.5c00cd0492a22fbce657.js:188 CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
abort @ scripts.5c00cd0492a22fbce657.js:188
polyfills.284a93d813815bf81e62.js:2 Unhandled Promise rejection: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info. ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:414083)
    at https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:415659
    at e.invoke (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:8955)
    at t.run (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4051)
    at https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:16035
    at e.invokeTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:9639)
    at t.runTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4714)
    at _ (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:11979) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:414083)
    at https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:415659
    at e.invoke (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:8955)
    at t.run (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4051)
    at https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:16035
    at e.invokeTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:9639)
    at t.runTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4714)
    at _ (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:11979)
Zone.__load_patch.n.onUnhandledError @ polyfills.284a93d813815bf81e62.js:2
polyfills.284a93d813815bf81e62.js:2 Unhandled Promise rejection: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info. ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:414083)
    at https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:415659
    at e.invoke (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:8955)
    at t.run (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4051)
    at https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:16035
    at e.invokeTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:9639)
    at t.runTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4714)
    at _ (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:11979) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
    at abort (https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:414083)
    at https://app.bitgo-test.com/scripts.5c00cd0492a22fbce657.js:188:415659
    at e.invoke (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:8955)
    at t.run (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4051)
    at https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:16035
    at e.invokeTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:9639)
    at t.runTask (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:4714)
    at _ (https://app.bitgo-test.com/polyfills.284a93d813815bf81e62.js:2:11979)
Zone.__load_patch.n.onUnhandledError @ polyfills.284a93d813815bf81e62.js:2
polyfills.284a93d813815bf81e62.js:2 Unhandled Promise rejection: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info. ; Zone: <root> ; Task: Promise.then ; Value: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info. undefined
Zone.__load_patch.n.onUnhandledError @ polyfills.284a93d813815bf81e62.js:2
angular.min.js:333 WARNING: Tried to load AngularJS more than once.
api/v1/client/constants:1 Failed to load resource: the server responded with a status of 520 ()
scripts.5c00cd0492a22fbce657.js:358 failed to fetch initial client constants from BitGo
(anonymous) @ scripts.5c00cd0492a22fbce657.js:358
api/v2/walletshares:1 Failed to load resource: the server responded with a status of 520 ()
api/v2/pendingapprovals:1 Failed to load resource: the server responded with a status of 520 ()
api/v1/pendingapprovals/filterable?enterpriseId=personal&getWallet=true&getLabels=true:1 Failed to load resource: the server responded with a status of 520 ()
api/v1/walletshare:1 Failed to load resource: the server responded with a status of 520 ()
api/auth/v1/accesstoken:1 Failed to load resource: the server responded with a status of 401 ()
api/auth/v1/accesstoken:1 Failed to load resource: the server responded with a status of 401 ()
api/auth/v1/accesstoken:1 Failed to load resource: the server responded with a status of 401 ()
scripts.5c00cd0492a22fbce657.js:424 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://app.bitgo-test.com/font/BitGo_iconfont.woff
polyfills.284a93d813815bf81e62.js:2 POST https://app.bitgo-test.com/api/v2/thbar/key 500
E @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
onScheduleTask @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleMacroTask @ polyfills.284a93d813815bf81e62.js:2
l @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ polyfills.284a93d813815bf81e62.js:2
P.a.<computed> @ polyfills.284a93d813815bf81e62.js:2
Request._end @ scripts.5c00cd0492a22fbce657.js:32
Request.end @ scripts.5c00cd0492a22fbce657.js:32
(anonymous) @ scripts.5c00cd0492a22fbce657.js:358
Promise._execute @ scripts.5c00cd0492a22fbce657.js:16
Promise._resolveFromExecutor @ scripts.5c00cd0492a22fbce657.js:16
Promise @ scripts.5c00cd0492a22fbce657.js:16
superagent.Request.end @ scripts.5c00cd0492a22fbce657.js:358
req.end @ scripts.5c00cd0492a22fbce657.js:358
req.then @ scripts.5c00cd0492a22fbce657.js:358
superagent.Request.result @ scripts.5c00cd0492a22fbce657.js:358
Keychains.add @ scripts.5c00cd0492a22fbce657.js:281
Keychains.createBitGo @ scripts.5c00cd0492a22fbce657.js:281
createBitGoKeychain @ legacy.696493355c7244a45a24.js:1
t.createBitGoKey @ legacy.696493355c7244a45a24.js:1
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
$digest @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
r @ main.91a35598b15d2013a7ce.js:2
t.__tryOrUnsub @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t._next @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t.emit @ main.91a35598b15d2013a7ce.js:2
Qd @ main.91a35598b15d2013a7ce.js:2
onHasTask @ main.91a35598b15d2013a7ce.js:2
e.hasTask @ polyfills.284a93d813815bf81e62.js:2
e._updateTaskCount @ polyfills.284a93d813815bf81e62.js:2
t._updateTaskCount @ polyfills.284a93d813815bf81e62.js:2
t.runTask @ polyfills.284a93d813815bf81e62.js:2
_ @ polyfills.284a93d813815bf81e62.js:2
t.invokeTask @ polyfills.284a93d813815bf81e62.js:2
p @ polyfills.284a93d813815bf81e62.js:2
h @ polyfills.284a93d813815bf81e62.js:2
XMLHttpRequest.send (async)
E @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
onScheduleTask @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleMacroTask @ polyfills.284a93d813815bf81e62.js:2
l @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ polyfills.284a93d813815bf81e62.js:2
P.a.<computed> @ polyfills.284a93d813815bf81e62.js:2
Request._end @ scripts.5c00cd0492a22fbce657.js:32
Request.end @ scripts.5c00cd0492a22fbce657.js:32
(anonymous) @ scripts.5c00cd0492a22fbce657.js:358
Promise._execute @ scripts.5c00cd0492a22fbce657.js:16
Promise._resolveFromExecutor @ scripts.5c00cd0492a22fbce657.js:16
Promise @ scripts.5c00cd0492a22fbce657.js:16
superagent.Request.end @ scripts.5c00cd0492a22fbce657.js:358
req.end @ scripts.5c00cd0492a22fbce657.js:358
req.then @ scripts.5c00cd0492a22fbce657.js:358
superagent.Request.result @ scripts.5c00cd0492a22fbce657.js:358
Keychains.add @ scripts.5c00cd0492a22fbce657.js:281
add @ legacy.696493355c7244a45a24.js:1
createAndAddKeychain @ legacy.696493355c7244a45a24.js:1
t.createBrowserBackupKey @ legacy.696493355c7244a45a24.js:1
t.createBackupKey @ legacy.696493355c7244a45a24.js:1
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
$digest @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
r @ main.91a35598b15d2013a7ce.js:2
t.__tryOrUnsub @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t._next @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t.next @ main.91a35598b15d2013a7ce.js:2
t.emit @ main.91a35598b15d2013a7ce.js:2
Qd @ main.91a35598b15d2013a7ce.js:2
onHasTask @ main.91a35598b15d2013a7ce.js:2
e.hasTask @ polyfills.284a93d813815bf81e62.js:2
e._updateTaskCount @ polyfills.284a93d813815bf81e62.js:2
t._updateTaskCount @ polyfills.284a93d813815bf81e62.js:2
t.runTask @ polyfills.284a93d813815bf81e62.js:2
_ @ polyfills.284a93d813815bf81e62.js:2
t.invokeTask @ polyfills.284a93d813815bf81e62.js:2
p @ polyfills.284a93d813815bf81e62.js:2
h @ polyfills.284a93d813815bf81e62.js:2
XMLHttpRequest.send (async)
E @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
onScheduleTask @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleMacroTask @ polyfills.284a93d813815bf81e62.js:2
l @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ polyfills.284a93d813815bf81e62.js:2
P.a.<computed> @ polyfills.284a93d813815bf81e62.js:2
Request._end @ scripts.5c00cd0492a22fbce657.js:32
Request.end @ scripts.5c00cd0492a22fbce657.js:32
(anonymous) @ scripts.5c00cd0492a22fbce657.js:358
Promise._execute @ scripts.5c00cd0492a22fbce657.js:16
Promise._resolveFromExecutor @ scripts.5c00cd0492a22fbce657.js:16
Promise @ scripts.5c00cd0492a22fbce657.js:16
superagent.Request.end @ scripts.5c00cd0492a22fbce657.js:358
req.end @ scripts.5c00cd0492a22fbce657.js:358
req.then @ scripts.5c00cd0492a22fbce657.js:358
superagent.Request.result @ scripts.5c00cd0492a22fbce657.js:358
Keychains.add @ scripts.5c00cd0492a22fbce657.js:281
add @ legacy.696493355c7244a45a24.js:1
createAndAddKeychain @ legacy.696493355c7244a45a24.js:1
t.createBrowserUserKey @ legacy.696493355c7244a45a24.js:1
t.createUserKey @ legacy.696493355c7244a45a24.js:1
t.createKeys @ legacy.696493355c7244a45a24.js:1
(anonymous) @ legacy.696493355c7244a45a24.js:1
instantiate @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ bitgo-client-vendor.min.js:3
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
Tt @ vendors~legacy.7e54182c0770870bacff.js:2
it @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
updateView @ bitgo-client-vendor.min.js:3
(anonymous) @ bitgo-client-vendor.min.js:3
$broadcast @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ bitgo-client-vendor.min.js:3
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
$digest @ vendors~legacy.7e54182c0770870bacff.js:2
$apply @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
w @ vendors~legacy.7e54182c0770870bacff.js:2
m.onload @ vendors~legacy.7e54182c0770870bacff.js:2
T @ polyfills.284a93d813815bf81e62.js:2
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
onInvokeTask @ main.91a35598b15d2013a7ce.js:2
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
t.runTask @ polyfills.284a93d813815bf81e62.js:2
t.invokeTask @ polyfills.284a93d813815bf81e62.js:2
p @ polyfills.284a93d813815bf81e62.js:2
h @ polyfills.284a93d813815bf81e62.js:2
load (async)
Z @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
onScheduleTask @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleEventTask @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ polyfills.284a93d813815bf81e62.js:2
E.a.set @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
$digest @ vendors~legacy.7e54182c0770870bacff.js:2
$apply @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
p @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
onInvokeTask @ main.91a35598b15d2013a7ce.js:2
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
t.runTask @ polyfills.284a93d813815bf81e62.js:2
t.invokeTask @ polyfills.284a93d813815bf81e62.js:2
a.useG.invoke @ polyfills.284a93d813815bf81e62.js:2
n.args.<computed> @ polyfills.284a93d813815bf81e62.js:2
setTimeout (async)
s @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
onScheduleTask @ polyfills.284a93d813815bf81e62.js:2
e.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleTask @ polyfills.284a93d813815bf81e62.js:2
t.scheduleMacroTask @ polyfills.284a93d813815bf81e62.js:2
l @ polyfills.284a93d813815bf81e62.js:2
(anonymous) @ polyfills.284a93d813815bf81e62.js:2
P.a.<computed> @ polyfills.284a93d813815bf81e62.js:2
i.defer @ vendors~legacy.7e54182c0770870bacff.js:2
u @ vendors~legacy.7e54182c0770870bacff.js:2
checkRMGEnterpriseAccess @ bitGo.js:148
invoke @ vendors~legacy.7e54182c0770870bacff.js:2
proceed @ bitgo-client-vendor.min.js:3
(anonymous) @ bitgo-client-vendor.min.js:3
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
$digest @ vendors~legacy.7e54182c0770870bacff.js:2
$apply @ vendors~legacy.7e54182c0770870bacff.js:2
(anonymous) @ vendors~legacy.7e54182c0770870bacff.js:2
dispatch @ scripts.5c00cd0492a22fbce657.js:424
q.handle @ scripts.5c00cd0492a22fbce657.js:424
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
onInvokeTask @ main.91a35598b15d2013a7ce.js:2
e.invokeTask @ polyfills.284a93d813815bf81e62.js:2
t.runTask @ polyfills.284a93d813815bf81e62.js:2
t.invokeTask @ polyfills.284a93d813815bf81e62.js:2
p @ polyfills.284a93d813815bf81e62.js:2
h @ polyfills.284a93d813815bf81e62.js:2
Show 113 more frames

```
## Steps to Reproduce

1. login to app.bitgo-test.com
2. create a thbar wallet
3. profit?

**Comment by argjv** [comment]
Hey @kaminskypavel, thanks for reporting this issue. The WASM error is actually a red herring, the underlying problem is with the `api/v2/thbar/key` request. We are testing a new internal system that doesn't seem to be working well for HBAR. This issue is only valid in testnet though.

For the Hedera21 hackathon, you can build and run the unit tests using the account-lib module in this project. The best way to test if the transaction is valid is to send it to the network!
Here is a script on how to do it using using account-lib:

```
const { Transaction, Client, AccountBalanceQuery } = require('@hashgraph/sdk');
const { account_2, account_3, multisigAccount } = require('../resources/testAccounts');
const { getBuilder, register, Hbar } = require('@bitgo/account-lib');

const factory = register('thbar', Hbar.TransactionBuilderFactory);

async function main() {

  // Show initial balance
   showBalance(account_3.operator.accountId, account_3.operator.privateKey);
  // Sign and build a transfer transaction for the first time
  const builder = getBuilder('thbar').getTransferBuilder();
  builder
    .fee({ fee: '100000000' })
    .source({ address: multisigAccount.accountId })
    .to(account_3.operator.accountId)
    .amount('1')
    .memo('Transfer from serialized')
    .node({nodeId: '0.0.3'})
    .sign({ key : multisigAccount.owners[0].privateKey});
  
  const tx = await builder.build();

  // Sign and build a second time
  const builder2 = getBuilder('thbar').getTransferBuilder();
  builder2.from(tx.toBroadcastFormat());
  builder2.sign({ key : multisigAccount.owners[1].privateKey});
  const tx2 = await builder2.build();

  // Sign and build a third time
  const builder3 = getBuilder('thbar').getTransferBuilder();
  builder3.from(tx2.toBroadcastFormat());
  builder3.sign({ key : multisigAccount.owners[2].privateKey});
  const tx3 = await builder3.build();
  
  // Wait to avoid INVALID_TRANSACTION_START error due to the clock being ahead of the consensus clock
  await sleep(2000)

  const client1 = Client.forTestnet().setOperator(account_2.operator.accountId, account_2.operator.privateKey);
  const transferTransaction = Transaction.fromBytes(Hbar.Utils.toUint8Array(tx3.toBroadcastFormat()));
  const transferCreateTransaction = await transferTransaction.execute(client1)

  const result = await transferCreateTransaction.getReceipt(client1);
  const txHash = (await transferCreateTransaction.getRecord(client1)).transactionHash
  const hash = new Buffer.from(txHash).toString('hex');
  
  console.log('Result ', result.status);


 console.log('https://explorer.kabuto.sh/testnet/transaction/' + hash);
 
  // Show balance after transfer
  showBalance(account_3.operator.accountId, account_3.operator.privateKey);
}

async function showBalance(accountId, privateKey) {
  const client = Client.forTestnet()
    .setOperator(accountId, privateKey);

  let balance = await new AccountBalanceQuery()
    .setAccountId(accountId)
    .execute(client)
  console.log(`${accountId} balance:`, balance);
}

function sleep(millis) {
  return new Promise(resolve => setTimeout(resolve, millis));
}

main().catch(console.error);
```
