### ISSUE TITLE
Error `invalid domian 'https://someurl.com' for coin 'talgo:16026728'`

### ISSUE THREAD

**Issue by plaucorp** [BitGo/BitGoJS#1237]
Error `invalid domian 'https://someurl.com' for coin 'talgo:16026728'` after this feature release: https://github.com/BitGo/BitGoJS/commit/29eb2a0ff320cc83727a54fe8a932e25359c831d

Full errror:

```
~/source/smalltests/bgo ❯ npm run start                                                                                                                              2m 40s  8.17.0

> bgo@1.0.0 start /Users/pablo/source/smalltests/bgo
> node index.js

/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/account.js:201
                throw new errors_1.InvalidDomainError(options.name, options.assetURL);
                ^

Error: invalid domain 'https://someurl.com/' for coin 'talgo:16026728'
    at InvalidDomainError.BitGoStaticsError [as constructor] (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/errors.js:23:23)
    at new InvalidDomainError (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/errors.js:82:28)
    at new AlgoCoin (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/account.js:201:23)
    at algoToken (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/account.js:563:26)
    at Object.talgoToken (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/account.js:598:12)
    at Object.<anonymous> (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/coins.js:546:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pablo/source/smalltests/bgo/node_modules/@bitgo/statics/dist/src/index.js:15:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bgo@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bgo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pablo/.npm/_logs/2021-06-21T10_00_41_300Z-debug.log
```

## Environment Details
* **OS:** Mac OS 11.4
* **Node Version:** 8.17.0
* **Yarn Version:** 
* **BitGoJS Version:** 11.13.0
* **BitGo Environment:** mainnet

## Expected Behavior
No error

## Current Behavior
Error `invalid domian 'https://someurl.com' for coin 'talgo:16026728'` on calling `const BitGo11 = require("bitgo");`

## Steps to Reproduce

1. Clone the repo: https://github.com/plaucorp/bgo-bug
2. `npm i --production`
3. `npm run start`
4.  Error appears

**Comment by OttoAllmendinger** [comment]
we will address this in an upcoming release

**Comment by plopezlpz** [comment]
still an issue in 11.17.0
