### ISSUE TITLE
After running `docker run -it -p 3080:3080 bitgosdk/express:latest` got 500 status returned

### ISSUE THREAD

**Issue by ukrit-himakoon** [BitGo/BitGoJS#1391]
After running, 
docker run -it -p 3080:3080 bitgosdk/express:latest , we tried to access transfer end-point but got status 500 returned with error below:

```
172.17.0.1 - local_express [11/Aug/2021:08:12:52 +0000] "GET /api/v2/teth/wallet/6019229614257d03360d116xxxxxx/transfer?allTokens=false&limit=100 HTTP/1.1" 500 148 "-" "mint/1.2.0"
TypeError: Cannot set property 'longStackSupport' of undefined
    at /var/bitgo-express/dist/src/clientRoutes.js:809:45
    at Layer.handle [as handle_request] (/var/bitgo-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/bitgo-express/node_modules/express/lib/router/index.js:317:13)
    at /var/bitgo-express/node_modules/express/lib/router/index.js:284:7
    at param (/var/bitgo-express/node_modules/express/lib/router/index.js:354:14)
    at param (/var/bitgo-express/node_modules/express/lib/router/index.js:365:14)
    at param (/var/bitgo-express/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/var/bitgo-express/node_modules/express/lib/router/index.js:410:3)
    at next (/var/bitgo-express/node_modules/express/lib/router/index.js:275:10)
    at /var/bitgo-express/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/var/bitgo-express/node_modules/raw-body/index.js:224:16)
    at done (/var/bitgo-express/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/var/bitgo-express/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
  ```
Repo Digest: `bitgosdk/express@sha256:e94ff61590d4f3d3f5a07230ab5945913e40e67e702f98068a47a31bd2268acf`
## Environment Details
* **OS:** MacOS
* **Node Version:** 
* **Yarn Version:** 
* **BitGoJS Version:** bitgosdk/express@sha256:e94ff61590d4f3d3f5a07230ab5945913e40e67e702f98068a47a31bd2268acf
* **BitGo Environment:** testnet

## Expected Behavior
should receive 200 status

## Steps to Reproduce

1. `docker run -it -p 3080:3080 bitgosdk/express:latest`
2. GET /api/v2/teth/wallet/6019229614257d03360d1169c38d002f/transfer?allTokens=false&limit=100
3. got 500 error

**Comment by ukrit-himakoon** [comment]
Any updates for this please?

**Comment by ukrit-himakoon** [comment]
Somehow it fixed in `sha256:ff7ae854364dc527772d6b8353e15c40e63bad9029f70adc407314b0fe9133a8`
