### ISSUE TITLE
Cannot get example working

### ISSUE THREAD

**Issue by JustinDrake** [BitGo/BitGoJS#14]
Followed the tutorial step-by-step (in particular, I did `npm install bitgo`). Below is the error I get:

```
node BitGoJS/example/auth.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'superagent'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/justin/Desktop/Duo-Money/backend/BitGoJS/src/bitgo.js:7:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by AlanVerbner** [comment]
Hello @JustinDrake, we have installed bitgo without any problem. 

I'm not sure if this is going to help you but it might give you an idea:
- We are using Node v4.2.3 and Npm 2.14.7. What versions are you using?
- If you try `npm view bitgo` what do you get? for example I can see `superagent: '^1.4.0'` in dependencies
- Did you try to clear npm cache?

**Comment by bencxr** [comment]
Closing due to inactivity
