### ISSUE TITLE
Failed at the keccak@1.4.0 rebuild script.

### ISSUE THREAD

**Issue by plaucorp** [BitGo/BitGoJS#1402]
## Environment Details
* **OS:** macOS big sur
* **Node Version:** v14.17.2
* **BitGoJS Version:** 12.0.0

## Expected Behavior
No errors during `npm i`

## Current Behavior
```
5 errors generated.
make: *** [Release/obj.target/keccak/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/.nvm/versions/node/v14.17.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/xxx/.nvm/versions/node/v14.17.2/bin/node" "/Users/xxx/.nvm/versions/node/v14.17.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/source/bgo-bug/node_modules/@bitgo/account-lib/node_modules/keccak
gyp ERR! node -v v14.17.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-08-13T06_19_56_738Z-debug.log
Keccak bindings compilation fail. Pure JS implementation will be used.
```

## Steps to Reproduce
1. `git clone git@github.com:plaucorp/bgo-bug.git`
2. `cd bgo-bug`
3. `npm i`
4. Error appears in console during installation

**Comment by elusieemmanuel** [comment]
Use yarn install not npm install
