### ISSUE TITLE
Error on tbtc address creation

### ISSUE THREAD

**Issue by nnbosko** [BitGo/BitGoJS#145]
On doing a simple wallet.createAddress({label: 'example1'}), I get an error from the SDK that goes like this:

`TypeError: Cannot read property 'address' of undefined
    at Wallet.createAndVerifyAddress (/home/bosko/Work/bitgo-profile/node_modules/bitgo/src/v2/wallet.js:601:99)
    at createAndVerifyAddress.next (<anonymous>)
    at createAndVerifyAddress.tryCatcher (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bosko/Work/bitgo-profile/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)`

The address, however, is correctly created and assigned the ID given.

**Comment by LeoKotschenreuther** [comment]
@nnbosko Which version of the SDK are you running and which coin is your wallet for?

**Comment by LeoKotschenreuther** [comment]
@nnbosko Actually, we could probably help you a lot more if you share with us the ID of your wallet and the email you are signed up with at BitGo. Since that is somewhat sensitive information, please don't post that here but rather contact our [Support](https://bitgo.freshdesk.com/support/tickets/new).

**Comment by nnbosko** [comment]
@LeoKotschenreuther I'm using bitgo 4.33.1. I'll contact the support team, thank you!

**Comment by nnbosko** [comment]
I was fetching the wallets a different way, @LeoKotschenreuther suggested a proper path and it worked! Closing the issue.

**Comment by nnbosko** [comment]
If anyone ever gets this error, it might be because you're doing this (the lines were input through the CLI manually, so all async results were resolved properly)

`const bg = require('bitgo')
const bitgojs = new bg.BitGo({env: 'test', accessToken: process.env.ACCESS_TOKEN})
let coin = bitgojs.coin('tbtc')
let wallets = {}
coin.wallets().list({}).then((ts) => {wallets = ts}) // the error is here; use coin.wallets().get({id:walletid})...
let wallet = wallets.wallets[0]
wallet.createAddress({label: 'addressid8'}).catch((err) => {console.dir(err)})`

Using wallets().get(...) cleared it up.
