### ISSUE TITLE
ping is not a function of bitgo

### ISSUE THREAD

**Issue by JustinDrake** [BitGo/BitGoJS#15]
This is my code, taken from the API docs:

```
var bitgo = require('bitgo');

bitgo.ping({}, function(err, res) {
    console.log(err, res);
});
```

I get:

```
bitgo.ping({}, function(err, res) {
      ^

TypeError: bitgo.ping is not a function
    at Object.<anonymous> (/Users/justin/Desktop/Duo-Money/backend/services/bitgo.js:7:7)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

I then tried looking at what is available in the `bitgo` object, and got:

```
for(var i in bitgo) {
    console.log(i);
}
```

```
BitGo
bitcoin
sjcl
bs58
setNetwork
getNetwork
```

What am I doing wrong?

**Comment by AlanVerbner** [comment]
@JustinDrake The following code is working for us:

```
// If importing via package
var BitGoJS = require('BitGoJS/src/index.js');
var bitgo = new BitGoJS.BitGo();

bitgo.ping({}, function(err, res) {
    // do stuff here
});
```

**Comment by bencxr** [comment]
Thanks alan, that's how it's meant to be used.
