### ISSUE TITLE
TXTZ address consolidation error.

### ISSUE THREAD

**Issue by DSkorobohatov** [BitGo/BitGoJS#1504]
## Environment Details
* **OS:** macOS Big Sur 11.5.2
* **Node Version:** 14.17.3
* **Yarn Version:** 1.22.5
* **BitGoJS Version:** dockerized  bitgosdk/express:latest
* **BitGo Environment:** test

## Expected Behavior
TXTZ addresses should be consolidated to the wallet after making request to `/api/v2/txtz/wallet/<wallet_id>/consolidateAccount/build` endpoint. Response status code should be 200.

## Current Behavior
`error 500: Failed to create any transactions.` on `/api/v2/txtz/wallet/{walletId}/consolidateAccount/build` endpoint.

## Steps to Reproduce

1. Create TXTZ wallet.
2. Add a lot of TXTZ to gas address.
3. Create new address using `/api/v2/txtz/wallet/{walletId}/address` endpoint.
4. Send some TXTZ to receive address just created (Check if transaction was successful in web dashboard).
5. Make request to `/api/v2/txtz/wallet/<wallet_id>/consolidateAccount/build` endpoint.
6. Response is:
```
{
    "error": "Failed to create any transactions. requestId=cktej0bip04bb065kstp44987",
    "name": "Internal",
    "requestId": "cktej0bip04bb065kstp44987",
    "context": {},
    "message": "Failed to create any transactions. requestId=cktej0bip04bb065kstp44987",
    "bitgoJsVersion": "12.0.0",
    "bitgoExpressVersion": "9.9.11"
}
```
7. Container logs:
```
error 500: Failed to create any transactions. requestId=cktej0bip04bb065kstp44987
Error: Failed to create any transactions. requestId=cktej0bip04bb065kstp44987
    at ApiResponseError.BitGoJsError [as constructor] (/var/bitgo-express/node_modules/bitgo/dist/src/errors.js:28:19)
    at new ApiResponseError (/var/bitgo-express/node_modules/bitgo/dist/src/errors.js:269:28)
    at errFromResponse (/var/bitgo-express/node_modules/bitgo/dist/src/api.js:62:12)
    at handleResponseError (/var/bitgo-express/node_modules/bitgo/dist/src/api.js:71:15)
    at /var/bitgo-express/node_modules/bitgo/dist/src/api.js:30:134
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by DSkorobohatov** [comment]
No progress, so I quit.
