### ISSUE TITLE
Failed To Start, Missing Module, Require Stack Error

### ISSUE THREAD

**Issue by bobozar** [BitGo/BitGoJS#1704]
I tried setting up the bitgoJS sdk, after installation it failed to start when I ran 'npm run start'. Besides, I got oldlock file error during installation.

## Environment Details
OS: Ubuntu 20.04
Node Version: v16.13.0
NPM Version: v8.1.0

Error below:

```
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile bitcoinjs-lib: No matching version found for bitcoinjs-lib@6.1.0-rc.3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for bitcoinjs-lib@6.1.0-rc.3 bitcoinjs-lib: No matching version found for bitcoinjs-lib@6.1.0-rc.3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '6.1.0-rc.3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.1.0', '0.1.3', '0.2.0',  '1.0.0', '1.0.1',  '1.0.2',
npm WARN old lockfile     '1.1.0', '1.1.1', '1.1.2',  '1.1.3', '1.1.4',  '1.1.5',
npm WARN old lockfile     '1.1.6', '1.1.7', '1.1.8',  '1.1.9', '1.1.10', '1.2.0',
npm WARN old lockfile     '1.3.0', '1.3.1', '1.4.1',  '1.4.2', '1.4.3',  '1.4.4',
npm WARN old lockfile     '1.4.5', '1.5.0', '1.5.1',  '1.5.2', '1.5.3',  '1.5.4',
npm WARN old lockfile     '1.5.5', '1.5.6', '1.5.7',  '1.5.8', '2.0.0',  '2.1.0',
npm WARN old lockfile     '2.1.1', '2.1.2', '2.1.3',  '2.1.4', '2.2.0',  '2.3.0',
npm WARN old lockfile     '3.0.0', '3.0.1', '3.0.2',  '3.0.3', '3.1.0',  '3.1.1',
npm WARN old lockfile     '3.2.0', '3.2.1', '3.3.0',  '3.3.1', '3.3.2',  '4.0.1',
npm WARN old lockfile     '4.0.2', '4.0.3', '4.0.4',  '5.0.0', '4.0.5',  '5.0.1',
npm WARN old lockfile     '5.0.2', '5.0.3', '5.0.4',  '5.0.5', '5.1.0',  '5.1.1',
npm WARN old lockfile     '5.1.2', '5.1.3', '5.1.4',  '5.1.5', '5.1.6',  '5.1.7',
npm WARN old lockfile     '5.1.8', '5.1.9', '5.1.10', '5.2.0', '6.0.0'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '6.0.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/ethereumjs-utils-old - Not found
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9)
npm WARN old lockfile  Could not fetch metadata for ethereumjs-utils-old@5.2.0 HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/ethereumjs-utils-old - Not found
npm WARN old lockfile     at /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:95:15
npm WARN old lockfile     at runMicrotasks (<anonymous>)
npm WARN old lockfile     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:741:9) {
npm WARN old lockfile   headers: [Object: null prototype] {
npm WARN old lockfile     date: [ 'Sun, 21 Nov 2021 17:29:24 GMT' ],
npm WARN old lockfile     'content-type': [ 'application/json' ],
npm WARN old lockfile     'content-length': [ '21' ],
npm WARN old lockfile     connection: [ 'keep-alive' ],
npm WARN old lockfile     'cf-ray': [ '6b1ba3d46aeb71f0-LHR' ],
npm WARN old lockfile     vary: [ 'Accept-Encoding' ],
npm WARN old lockfile     'expect-ct': [
npm WARN old lockfile       'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
npm WARN old lockfile     ],
npm WARN old lockfile     server: [ 'cloudflare' ],
npm WARN old lockfile     'x-fetch-attempts': [ '1' ],
npm WARN old lockfile     'x-local-cache-status': [ 'skip' ]
npm WARN old lockfile   },
npm WARN old lockfile   statusCode: 404,
npm WARN old lockfile   code: 'E404',
npm WARN old lockfile   method: 'GET',
npm WARN old lockfile   uri: 'https://registry.npmjs.org/ethereumjs-utils-old',
npm WARN old lockfile   body: { error: 'Not found' },
npm WARN old lockfile   pkgid: 'ethereumjs-utils-old@5.2.0'
npm WARN old lockfile }
Killed#############⸩ ⠇ reify:fsevents: sill reify mark deleted [
```

When I enter the 'npm run start' command I got the below error:

```
> @bitgo/express@9.10.1 start
> node bin/bitgo-express

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../dist/src/expressApp'
Require stack:
- /var/www/example.com/bgo/bitgojs/modules/express/bin/bitgo-express
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/example.com/bgo/bitgojs/modules/express/bin/bitgo-express:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/example.com/bgo/bitgojs/modules/express/bin/bitgo-express' ]
}
```

What am I missing?

**Comment by mmcshinsky-bitgo** [comment]
Hi @bobozar. I have gone ahead and run against the versions above with success. Thank you for providing those. There have been a number of updates between the bug report and now including package-lock.json updates. Are you able to reproduce this issue currently with the latest changes?

**Comment by bobozar** [comment]
Still having issues.. @mmcshinsky-bitgo

**Comment by mmcshinsky-bitgo** [comment]
@bobozar I've gone ahead and created a pull request for your first issue [here](https://github.com/BitGo/BitGoJS/pull/2113). It looks like your second issue stems from the command looking to run the `expressApp` file from the `dist` folder which would require you to run `npm run build` first to generate that folder.
