### ISSUE TITLE
Create addresses semi-working on test platform

### ISSUE THREAD

**Issue by kytwb** [BitGo/BitGoJS#19]
I get the following stacktrace:

```
api_1 | AssertionError: Not enough pubKeys provided
api_1 |     at Object.multisigOutput (/app/node_modules/bitcoinjs-lib/src/scripts.js:206:3)
api_1 |     at Object.Util.p2shMultisigOutputScript (/app/node_modules/bitgo/src/util.js:21:30)
api_1 |     at calcAddress (/app/node_modules/bitgo/src/wallet.js:214:23)
api_1 |     at Wallet.validateAddress (/app/node_modules/bitgo/src/wallet.js:219:22)
api_1 |     at /app/node_modules/bitgo/src/wallet.js:185:12
api_1 |     at _fulfilled (/app/node_modules/bitgo/node_modules/q/q.js:794:54)
api_1 |     at self.promiseDispatch.done (/app/node_modules/bitgo/node_modules/q/q.js:823:30)
api_1 |     at Promise.promise.promiseDispatch (/app/node_modules/bitgo/node_modules/q/q.js:756:13)
api_1 |     at /app/node_modules/bitgo/node_modules/q/q.js:564:44
api_1 |     at flush (/app/node_modules/bitgo/node_modules/q/q.js:110:17)
api_1 |     at /app/node_modules/async-listener/glue.js:188:31
api_1 |     at doNTCallback0 (node.js:417:9)
api_1 |     at process._tickCallback (node.js:346:13)
```

It does create the addresses on the test platform, but the promise being rejected I need to use a hack-ish way to get the newly created address information.

**Comment by bencxr** [comment]
this works with promises now
