### ISSUE TITLE
[sdk-coin-algo] Question: How do we register custom ASA tokens?

### ISSUE THREAD

**Issue by surhud004** [BitGo/BitGoJS#2763]
Hello team,
How do we register custom ASA tokens (for example, USDC on `testnet`) with `@bitgo/sdk-coin-algo`?
I tried registering with the following snippet but ran into an error -
```
...\node_modules\@bitgo\sdk-core\dist\src\bitgo\baseCoin\baseCoin.js:41
        this._url = this.bitgo.url('/', 2);
                               ^

TypeError: Cannot read properties of undefined (reading 'url')
    at new BaseCoin (...\node_modules\@bitgo\sdk-core\dist\src\bitgo\baseCoin\baseCoin.js:41:32)   
    at new Algo (...\node_modules\@bitgo\sdk-coin-algo\dist\src\algo.js:40:9)
    at Function.createInstance (...\node_modules\@bitgo\sdk-coin-algo\dist\src\algo.js:45:16)
```

Here is my code snippet -
```
import { BitGoAPI } from '@bitgo/sdk-api'
import { AlgoToken } from '@bitgo/sdk-coin-algo'

const sdk = new BitGoAPI({
  env: 'test',
  accessToken: 'apiKey',
})

sdk.register('talgo:USDC-10458941', AlgoToken.createInstance())

const wallet = await sdk.coin('talgo:USDC-10458941').wallets().get({
    id: walletId,
})
```

Environment details:
`@bitgo/sdk-api: ^1.1.1`
`@bitgo/sdk-coin-algo: ^1.1.1`

**Comment by surhud004** [comment]
For devs running into a similar issue, here's the solution I figured out from the [algo unit tests](https://github.com/BitGo/BitGoJS/blob/master/modules/sdk-coin-algo/test/unit/algoToken.ts#L14).

```
import { BitGoAPI } from '@bitgo/sdk-api'
import { AlgoToken } from '@bitgo/sdk-coin-algo'

const sdk = new BitGoAPI({
  env: 'test',
  accessToken: 'apiKey',
})

const usdcConstructor = AlgoToken.createTokenConstructors().find((coins) => coins.name === 'talgo:USDC-10458941').coinConstructor

sdk.register('talgo:USDC-10458941', usdcConstructor)

const wallet = await sdk.coin('talgo:USDC-10458941').wallets().get({
    id: walletId,
})
```
For other supported ASA tokens, the coin name can be found from [coins.ts](https://github.com/BitGo/BitGoJS/blob/master/modules/statics/src/coins.ts).
