### ISSUE TITLE
Module Not found ../dist/src/expressApp

### ISSUE THREAD

**Issue by Kuldeepnb03** [BitGo/BitGoJS#294]
Hi, I cloned the repository and try to run the below command inside the bin folder
./bitgo-express --debug --port 3080 --env test --bind localhost

Getting error as
Error: Cannot find module '../dist/src/expressApp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/*****/BitGoJS/bin/bitgo-express:5:66)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

How to fix this?

**Comment by tylerlevine** [comment]
Are you attempting to install as root (super user)?

If so, you'll need to install with `npm install --unsafe-perm` or run the postinstall script manually after installing with `npm explore bitgo -- npm run postinstall`.

You can also run bitgo-express from the npm package using `npm install bitgo && npm explore bitgo -- bin/bitgo-express`

**Comment by Kuldeepnb03** [comment]
Thank you @tylerlevine.

Am not attempting to install as a root.

The second method worked for me. Thank you very much
