### ISSUE TITLE
Cannot read property 'network' of undefined 

### ISSUE THREAD

**Issue by rihbyne** [BitGo/BitGoJS#37]
Hi there,
I have npm installled bitgo version v2.2.0
When I try to make an instance using
`var bitgo = new BitGo.BitGo({ accessToken: process.env.BITGO_ACCESS_TOKEN })`

Its throwing this TypeError
`TypeError: Cannot read property 'network' of undefined
    at new BitGo (/home/rihan/codefarm/nodejs/auto-cashout/node_modules/bitgo/src/bitgo.js:197:52)
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)`

PS - This was not happening yesterday. Only today I am facing this issue

**Comment by Melvillian** [comment]
Do you have the BITGO_ENV environment variable set? If so, what is it's value? If you want to use production it should be set to 'prod'
