### ISSUE TITLE
internal/modules/cjs/loader.js:638

### ISSUE THREAD

**Issue by azerotho** [BitGo/BitGoJS#374]
Hi, I cloned the repository and try to run the below command inside the `/root/BitGoJS/modules/express/bin` folder

`./bitgo-express --debug --port 3080 --env test --bind localhost`

And I get the following error:

`root@ip:~/BitGoJS/modules/express/bin# ./bitgo-express --debug --port 3080 --env test --bind localhost
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'http-proxy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/BitGoJS/modules/express/dist/src/expressApp.js:31:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/BitGoJS/modules/express/bin/bitgo-express:5:66)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
root@ip:~/BitGoJS/modules/express/bin# internal/modules/cjs/loader.js:638
`

How to fix this?

**Comment by cooncesean** [comment]
Have you npm installed the dependencies?

**Comment by azerotho** [comment]
Yes, I have already installed it, following the instructions but now I have a slight problem to start the production environment.

  since I do not know what to do so that it is no longer a test environment but a production one ...

Use the following:

`docker run -it --rm -p 3080:3080 bitgo/express:latest`

And he gives me this message: 
`BitGo-Express running
Environment: test
Base URI: http://0.0.0.0:3080`

How do I start the production environment?
