### ISSUE TITLE
Unable to get balances

### ISSUE THREAD

**Issue by christiansaiki** [BitGo/BitGoJS#399]
I'm getting this error from time to time
```
stack:Error: Unable to get balances for tbch requestId=31e25f0288c6bf546559-0000\n    at 
errFromResponse (/opt/app/node_modules/bitgo/src/bitgo.js:87:15)\n    at handleResponseError 
(/opt/app/node_modules/bitgo/src/bitgo.js:104:11)\n    at PromiseShim.applySegment 
(/opt/app/node_modules/newrelic/lib/shim/shim.js:1387:20)\n    at __NR_wrappedThenHandler 
(/opt/app/node_modules/newrelic/lib/shim/promise-shim.js:419:22)\n    at tryCatcher 
(/opt/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler 
(/opt/app/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise 
(/opt/app/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 
(/opt/app/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises 
(/opt/app/node_modules/bluebird/js/release/promise.js:690:18)\n    at _drainQueueStep 
(/opt/app/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue 
(/opt/app/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues 
(/opt/app/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues [as
 _onImmediate] (/opt/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback 
(timers.js:694:18)\n    at tryOnImmediate (timers.js:665:5)\n    at processImmediate (timers.js:647:5)

updatedAt:{}}
```

What does it mean?
How can I fix this issue. It happens sometimes. Is it something to do with testnet?

Thanks!

**Comment by tylerlevine** [comment]
Hey @christiansaiki,

This is usually caused by some intermittent failure in our testnet backend, and not the BitGoJS SDK itself. If you email `support@bitgo.com`, they can look into this particular request to see exactly what failed.
