### ISSUE TITLE
Error: Unable to resolve module @brandonblack/musig/base_crypto

### ISSUE THREAD

**Issue by Mustafa-Agha** [BitGo/BitGoJS#4052]
I'm getting this error when I try running @bitgo/utxo-lib on react-native app using expo

to reproduce just install @bitgo/utxo-lib on any expo application and then try running it on ios/android/web

you'll get the below error

**Any Idea how to solve this problem?**

```
> Task :app:createBundleDirectDebugJsAndAssets
error Unable to resolve module @brandonblack/musig/base_crypto from /home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js: @brandonblack/musig/base_crypto could not be found within the project or in these directories:
  ../../node_modules/@bitgo/utxo-lib/node_modules
  ../../node_modules
  
  ../../node_modules
   9 | // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  10 | // @ts-ignore base_crypto is exported as a subPath export, ignoring since compiler complains about importing like this
Error: Unable to resolve module @brandonblack/musig/base_crypto from /home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js: @brandonblack/musig/base_crypto could not be found within the project or in these directories:
> 11 | const baseCrypto = require("@brandonblack/musig/base_crypto");
  ../../node_modules/@bitgo/utxo-lib/node_modules
     |                             ^
  12 | const musig_1 = require("@brandonblack/musig");
  13 | necc.utils.sha256Sync = (...messages) => {
  14 |     const sha256 = createHash('sha256');
  ../../node_modules
  
  ../../node_modules
   9 | // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  10 | // @ts-ignore base_crypto is exported as a subPath export, ignoring since compiler complains about importing like this
> 11 | const baseCrypto = require("@brandonblack/musig/base_crypto");
     |                             ^
  12 | const musig_1 = require("@brandonblack/musig");
  13 | necc.utils.sha256Sync = (...messages) => {
  14 |     const sha256 = createHash('sha256');
    at ModuleResolver.resolveDependency (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 7)
    at async Graph._processModule (/home/USER_NAME/Desktop/work-space/pecunia/web-wallets/my-app-v4.15.0/node_modules/metro/src/DeltaBundler/Graph.js:263:5)

> Task :app:createBundleDirectDebugJsAndAssets FAILED
```

**Comment by dimisus** [comment]
Issue still exists.

**Comment by HaykSahakyan** [comment]
facing the same issue

**Comment by HaykSahakyan** [comment]
Error: Cannot find module '@brandonblack/musig/base_crypto'
at Object.<anonymous> (/some path/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js:11:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/utxo-lib/dist/src/noble_ecc.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/utxo-lib/dist/src/bitgo/keyutil.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/utxo-lib/dist/src/bitgo/index.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/utxo-lib/dist/src/index.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/sdk-core/dist/src/account-lib/util/crypto.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/sdk-core/dist/src/account-lib/baseCoin/ed25519KeyPair.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/sdk-core/dist/src/account-lib/baseCoin/index.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/sdk-core/dist/src/account-lib/index.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/@bitgo/sdk-core/dist/src/index.js',
    '/media/hayk/18.04/home/hayk/work/Serozh/my/cc-bank/node_modules/bitgo/dist/src/index.js',
...
  ]
}

Node.js v20.11.0

**Comment by kyimoemin** [comment]
here is the solution, I found it somewhere else but couldn't find it anymore. you have to patch `@bitgo/utxo-lib` and `@brandonblack/musig` packages. 


1. add these lines in `exports` of `@brandonblack/music/package.json`
``` git
...
"./base_crypto": {
       "import": "./lib/esm/base_crypto.js",
       "default": "./lib/base_crypto.js"
+    },
+    "./lib/base_crypto": {
+      "import": "./lib/esm/base_crypto.js",
+      "default": "./lib/base_crypto.js"
     }
   },
   "jest": {
...
``` 

2. and this in `@bitgo/utxo-lib/distt/src/noble_ecc.js`

```  git

 const bip32_1 = require("bip32");
 // eslint-disable-next-line @typescript-eslint/ban-ts-comment
 // @ts-ignore base_crypto is exported as a subPath export, ignoring since compiler complains about importing like this
-const baseCrypto = require("@brandonblack/musig/base_crypto");
+const baseCrypto = require("@brandonblack/musig/lib/base_crypto");
 const musig_1 = require("@brandonblack/musig");
 necc.utils.sha256Sync = (...messages) => {
     const sha256 = createHash('sha256');
    
```

**Comment by Mustafa-Agha** [comment]
@kyimoemin this issue was solved in this github repo, https://github.com/BitGo/BitGoJS/issues/4008
and I also requested a PR, hopefully the devs make the proper changes.
