### ISSUE TITLE
cannot find module

### ISSUE THREAD

**Issue by brijitjoshua** [BitGo/BitGoJS#44]
> var BitGo = require('bitgo');
Error: Cannot find module 'bitgo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)

**Comment by thomas4019** [comment]
Please try running "npm install bitgo" in your project. It seems that bitgo did not install correctly.
