### ISSUE TITLE
BitGo is not a constructor

### ISSUE THREAD

**Issue by brijitjoshua** [BitGo/BitGoJS#45]
TypeError: BitGo.BitGo is not a constructor
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

**Comment by BhargavaMallik** [comment]
TypeError: BitGo.BitGo is not a constructor
    at Object.<anonymous> (C:\projects\BitGoJS\index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by arik-so** [comment]
What code are you running to produce this error?
