### ISSUE TITLE
sdk env notset

### ISSUE THREAD

**Issue by BhargavaMallik** [BitGo/BitGoJS#46]
$ node index
BitGo SDK env not set - defaulting to testnet at test.bitgo.com.
{ Error: unauthorized
    at errFromResponse (C:\projects\BitGoJS\node_modules\bitgo\src\bitgo.js:76:1

    at handleResponseError (C:\projects\BitGoJS\node_modules\bitgo\src\bitgo.js:
:11)
    at _rejected (C:\projects\BitGoJS\node_modules\q\q.js:804:24)
    at C:\projects\BitGoJS\node_modules\q\q.js:830:30
    at Promise.when (C:\projects\BitGoJS\node_modules\q\q.js:1064:31)
    at Promise.promise.promiseDispatch (C:\projects\BitGoJS\node_modules\q\q.js:
8:41)
    at C:\projects\BitGoJS\node_modules\q\q.js:564:44
    at flush (C:\projects\BitGoJS\node_modules\q\q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  status: 401,
  result: { error: 'unauthorized' },
  invalidToken: true }
undefined

**Comment by ravingalaxy** [comment]
I am facing the following problem while sending coin using bitgo sendcoin api....


Error: no unspents available on wallet
    at collectInputs (/var/www/html/BitGoJS/src/transactionBuilder.js:326:13)
    at _fulfilled (/var/www/html/BitGoJS/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/var/www/html/BitGoJS/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/var/www/html/BitGoJS/node_modules/q/q.js:756:13)
    at /var/www/html/BitGoJS/node_modules/q/q.js:564:44
    at flush (/var/www/html/BitGoJS/node_modules/q/q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
undefined

**Comment by thomas4019** [comment]
The message about the sdk environment not being set is normal. We have a test and prod environment so you can pass the ['env' variable to explicitly choose your environment](https://www.bitgo.com/api/v2/#software-development-kit), otherwise we default to test.
The reason you are getting the unauthorized response means there is something wrong with your token. Please try creating a new developer access token as explained in [our docs here](https://www.bitgo.com/api/v2/#api-access-tokens).

**Comment by LeoKotschenreuther** [comment]
Hi @BhargavaMallik 
Did @thomas4019 response help you?
If you still have questions about this feel free to reopen this issue or to contact BitGo support at support@bitgo.com
