### ISSUE TITLE
Error while Starting production environment

### ISSUE THREAD

**Issue by sitewarlock** [BitGo/BitGoJS#562]
Whenever i pass the below code in /BitGoJS/modules/express/bin#...
`./bitgo-express --port <port> --env prod --bind <domain> --disablessl`

It gives me the below error
`module.js:549
    throw err;
    ^

Error: Cannot find module '../dist/src/expressApp'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/BitGoJS/modules/express/bin/bitgo-express:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`

Please help me!!

**Comment by minherc** [comment]
try this
```
./bitgo-express --port 4000 --env prod --bind localhost --disablessl
```

**Comment by minherc** [comment]
for me it's not worked :
```
bitgojs/modules/express/bin# ./bitgo-express --disableenvcheck --port 4000 --env prod --bind localhost --disablessl --disableenvcheck

Fatal error: NODE_ENV should be set to production when running against prod environment. Use --disableenvcheck if you really want to run in a non-production node configuration.
Error: NODE_ENV should be set to production when running against prod environment. Use --disableenvcheck if you really want to run in a non-production node configuration.

```

**Comment by cooncesean** [comment]
@sitewarlock is this still an issue for you?
