### ISSUE TITLE
ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by giangitman** [BitGo/BitGoJS#62]
Get this error when try to create an wallet by CURL:

ReferenceError: _ is not defined
    at Wallets.add (/var/www/html/BitGoJS/src/wallets.js:468:53)
    at /var/www/html/BitGoJS/src/wallets.js:374:17
    at tryCatcher (/var/www/html/BitGoJS/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

**Comment by omaidf** [comment]
Hello,

Could you please send us your cURL request?

**Comment by huygo93123** [comment]
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESS_TOKEN" -d '{ "passphrase": "superlongpassword", "label": "My BitGo Wallet 2" }' http://localhost:3080/api/v1/wallets/simplecreate

{"error":"_ is not defined","message":"_ is not defined"}

**Comment by arik-so** [comment]
Hi,

Did you try running npm install?

**Comment by huygo93123** [comment]
Of course ! i ran "npm install"  but it is ok  after fix line 468: "!_.isNumber(params.m) || !_.isNumber(params.n)" in file "src/wallets.js"

**Comment by nowaksmini** [comment]
Hi, problem blocks my application, is there any chance you will fix this error?

**Comment by Aradea08** [comment]
I also face this problem in V1, while support says not recommended to use V2 (they said still in alpha mode). My V2 lib has no problem, run well from create wallet - send btc, but error in V1.

anyone know how to solve it ?

Here's the error ; 

ReferenceError: _ is not defined
    at Wallets.add (/var/www/html/BitGoJS/src/wallets.js:468:53)
    at /var/www/html/BitGoJS/src/wallets.js:374:17
    at tryCatcher (/var/www/html/BitGoJS/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

```
Error: Could not create wallet!
    at /var/www/html/BitGoJS/example/createwallet.js:39:40
    at tryCatcher (/var/www/html/BitGoJS/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.errorAdapter (/var/www/html/BitGoJS/node_modules/bluebird/js/main/nodeify.js:36:34)
    at Promise._settlePromiseAt (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/var/www/html/BitGoJS/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by LeoKotschenreuther** [comment]
Will close since there has been no activity for almost a year. Our V2 wallets are also used by new customers for quite some time already so you should be good to use them.

Please reopen if this is still an issue.
