### ISSUE TITLE
Can't compile v4.8.0

### ISSUE THREAD

**Issue by you-fail-me** [BitGo/BitGoJS#70]
Downloaded zip of v4.8.0, trying to compile a browser bundle, getting errors:
```
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/node" "/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/npm" "run-script" "compile"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bitgo@4.8.0 compile: `mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitgo@4.8.0 compile script 'mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitgo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitgo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bitgo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yxfxmx/Dev/BitGoJS-4.8.0/npm-debug.log
```
The mentioned `npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'compile' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle bitgo@4.8.0~precompile: bitgo@4.8.0
6 silly lifecycle bitgo@4.8.0~precompile: no script for precompile, continuing
7 info lifecycle bitgo@4.8.0~compile: bitgo@4.8.0
8 verbose lifecycle bitgo@4.8.0~compile: unsafe-perm in lifecycle true
9 verbose lifecycle bitgo@4.8.0~compile: PATH: /Users/yxfxmx/.nvm/versions/node/v6.9.5/lib/node_modules/npm/bin/node-gyp-bin:/Users/yxfxmx/Dev/BitGoJS-4.8.0/node_modules/.bin:/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/bin:/Users/yxfxmx/Library/Android/sdk/tools:/Users/yxfxmx/Library/Android/sdk/platform-tools:/Users/yxfxmx/Library/Android/sdk/build-tools/25.0.0
10 verbose lifecycle bitgo@4.8.0~compile: CWD: /Users/yxfxmx/Dev/BitGoJS-4.8.0
11 silly lifecycle bitgo@4.8.0~compile: Args: [ '-c',
11 silly lifecycle   'mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js' ]
12 silly lifecycle bitgo@4.8.0~compile: Returned: code: 1  signal: null
13 info lifecycle bitgo@4.8.0~compile: Failed to exec compile script
14 verbose stack Error: bitgo@4.8.0 compile: `mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/yxfxmx/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/yxfxmx/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bitgo@4.8.0
16 verbose cwd /Users/yxfxmx/Dev/BitGoJS-4.8.0
17 error Darwin 16.7.0
18 error argv "/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/node" "/Users/yxfxmx/.nvm/versions/node/v6.9.5/bin/npm" "run-script" "compile"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bitgo@4.8.0 compile: `mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js`
22 error Exit status 1
23 error Failed at the bitgo@4.8.0 compile script 'mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bitgo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bitgo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bitgo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
What is the problem here? How can I resolve? I also had issues when doing `npm install` before compiling: https://github.com/BitGo/BitGoJS/issues/69
Could these be related?

**Comment by Melvillian** [comment]
You should use `npm install` to install these dependencies. I'm not sure what other problems you'll see from using a zip file, but I bet it is less supported than doing the normal approach (downloading through `npm install`)

**Comment by you-fail-me** [comment]
It looks like the reason is not fetching zip from github vs npm install, the actual error I'm getting when running `npm run-script compile` is
```
SyntaxError: Unexpected token: name (error) while parsing file: /Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/src/bitgo.js
    at JS_Parse_Error.get (eval at <anonymous> (/Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/node_modules/uglifyify/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at Readable.errorExit (/Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/node_modules/browserify/bin/cmd.js:68:26)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at Labeled.<anonymous> (/Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/node_modules/read-only-stream/index.js:28:44)
    at emitOne (events.js:96:13)
    at Labeled.emit (events.js:188:7)
    at Labeled.<anonymous> (/Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/node_modules/stream-splicer/index.js:130:18)
    at emitOne (events.js:101:20)
    at Labeled.emit (events.js:188:7)
```
which seems to be related to minifier, that's what I've found regarding this: https://github.com/webpack/webpack/issues/2972#issuecomment-261705632

Running without minification (`compile-dbg`) doesn't throw that, but instead I'm getting `Error: Cannot find module 'bufferutil' from '/Users/yxfxmx/Downloads/bitgo/node_modules/bitgo/node_modules/ws/lib'`. Looking at that folder (`...node_modules/ws/lib`) reveals that it has no index file

**Comment by you-fail-me** [comment]
So, looks like these were really errors with minifier and `bufferutil` module. The first error is because uglifyjs is unable to process es2015+, to solve it I had to apply global babelify transform before minification (the resulting command looks as follows: `"mkdir -p browser && ./node_modules/.bin/browserify ./src/index.js -t [ babelify --global --presets [ env ] ] --exclude superagent-proxy --exclude morgan -s BitGoJS -g uglifyify -o browser/BitGoJS-min.js"`), to fix the second error - to manually add `bufferutil` and `utf-8-validate` modules. Then it worked.
But the minified bundle I'm getting is 2MB. Is there a way to reduce it? Or did I make some mistake which could lead to it?
