### ISSUE TITLE
I am facing problem while sending btc using bitgojs sendcoins api

### ISSUE THREAD

**Issue by ravingalaxy** [BitGo/BitGoJS#76]
All part of api working fine but sendcoins is not working fine i m sending the required parameters in a required format. Please solve my problem.

Error: no unspents available on wallet
    at collectInputs (/var/www/html/BitGoJS/src/transactionBuilder.js:326:13)
    at _fulfilled (/var/www/html/BitGoJS/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/var/www/html/BitGoJS/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/var/www/html/BitGoJS/node_modules/q/q.js:756:13)
    at /var/www/html/BitGoJS/node_modules/q/q.js:564:44
    at flush (/var/www/html/BitGoJS/node_modules/q/q.js:110:17)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
undefined

**Comment by mariyaVj** [comment]
It may be because you don't have enough balance in your wallet to send coins, try to buy some test coins

**Comment by ravingalaxy** [comment]
i have 2.2500 BTC  and try to send 1BTC

**Comment by thomas4019** [comment]
Hi ravingalaxy, it looks like you may be using 2 versions of our SDK, version 3.1.0 and 4.13.0. When using the older version, 3.1.0, it will fail to send coins because your inputs are segwit and our older SDK clients do not know how to use those inputs. Please make sure you only use our latest API and let us know if you're still having an issue.

**Comment by ravingalaxy** [comment]
While i am using the new one updated Bitgo api, there is different error found,

{ Error: needs unlock
    at errFromResponse (/var/www/html/BitGoJS/src/bitgo.js:82:15)
    at handleResponseError (/var/www/html/BitGoJS/src/bitgo.js:99:11)
    at tryCatcher (/var/www/html/BitGoJS/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  status: 401,
  result: 
   { error: 'needs unlock',
     needsOTP: true,
     needsUnlock: true,
     name: 'Error',
     requestId: 'cj9zcctb93kqmj3rs7cqpzl2m' },
  needsOTP: true }

undefined

**Comment by thomas4019** [comment]
You need to call the unlock endpoint with an OTP code before you will be able to send coins. Read about it in our [API](https://bitgo.github.io/bitgo-docs/#unlock).

**Comment by ravingalaxy** [comment]
Thank you so much, now its working. will you please suggest me that how to get otp (2Factor Auth code) using api so that i can use it at the time of sendcoin through api.

**Comment by ravingalaxy** [comment]
i am using the below code to generate otp but it did not response anything,

bitgo.sendOTP({forceSMS: true}, function callback(err) {
  if (err) {
         // handle error
  }
     // etc
});

**Comment by thomas4019** [comment]
Hi ravingalaxy,
The easiest way to not need to unlock frequently is to use an access token. Make sure the txValueLimit on the token is high enough that you can do the transactions you want to do. Then you won't need to call unlock before sendcoins.

**Comment by ravingalaxy** [comment]
Hi thomas4019,
I am using access token Still not working below is my input file code and output code. Please help,

INPUT FILE CODE 
var BitGoJS = require('./BitGoJS/src/index.js');
var accessToken = process.argv[2];
var walletId = process.argv[3];
var env = process.argv[4];
var walletPassphrase = process.argv[5];
var amount =process.argv[6];
var address =process.argv[7];

var bitgo = new BitGoJS.BitGo({env: env, accessToken: accessToken});
bitgo.session({}, function callback(err, session) {
 
bitgo.wallets().get({ "id": walletId }, function callback(err, wallet) {  
	  if (!err)
	  { 
wallet.sendCoins({
                         address: address, 
                         amount: parseFloat(amount) * 1e8,
                         walletPassphrase: walletPassphrase}, function(err, result) {
				if (err) {console.dir(err);}
				console.log(JSON.stringify(result));
			}); 
	  }	  
	});
	
	console.dir(session);
});

**Comment by thomas4019** [comment]
Hi ravingalaxy,
It appears that you called unlock with that token. You shouldn't need to call unlock when you use a token and if you do it can cause a problem. From our docs:

> "The token will come unlocked by default with your specified spending limit. Do not attempt to unlock the token again via API as this will reset the unlock."

Please try creating a new token and then sending coins without calling unlock.

**Comment by ravingalaxy** [comment]
hi thomas4019,

still having same problem while i have created new token and try to sending coins on testnet without calling unlock, and the response is below,

v2xfcaea49ed722d0391236b7d30cc8088aa8a7f78f59d09f7f9c0f092563a7da8a

Getting wallet..
Balance is: 2.1500
Error sending coins!
{ Error: needs unlock
    at errFromResponse (/var/www/html/BitGoJS/src/bitgo.js:82:15)
    at handleResponseError (/var/www/html/BitGoJS/src/bitgo.js:99:11)
    at tryCatcher (/var/www/html/BitGoJS/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/html/BitGoJS/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/html/BitGoJS/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  status: 401,
  result: 
   { error: 'needs unlock',
     needsOTP: true,
     needsUnlock: true,
     name: 'Error',
     requestId: 'cja0vyab15cdkj3rtlwas4up3' },
  needsOTP: true }

**Comment by ravingalaxy** [comment]
MY Code is below

var BitGoJS = require('./BitGoJS/src/index.js');
var accessToken = process.argv[2];
var env = process.argv[4];
var amount =process.argv[6];
var address =process.argv[7];
var walletId = process.argv[3];
var walletPassphrase = process.argv[5];

var bitgo = new BitGoJS.BitGo({env: env, accessToken: accessToken});

bitgo.wallets().get({ "id": walletId }, function callback(err, wallet) {  
	  if (!err)
	  { 
			wallet.sendCoins({address: address, amount: parseFloat(amount) * 1e8,walletPassphrase:  walletPassphrase}, function(err, result) {
				if (err) {console.dir(err);}
				console.log(JSON.stringify(result));
			}); 
	  }	  
	});

**Comment by ravingalaxy** [comment]
Hi thomas4019,

My problem is solved now. 

Thank you so much for giving me your time and help.

**Comment by thomas4019** [comment]
I'm glad it's working for you now.

**Comment by 99Percent** [comment]
I am having the same issue, I will contact support@bitgo.com

**Comment by 99Percent** [comment]
Support promptly told me that the access token must have spending limits defined. I created another token with such spending limits and my problem was solved. I no longer get the needsOTP message and was able to send the coins.
