### ISSUE TITLE
Bitgo not Authentication with Access Token

### ISSUE THREAD

**Issue by ukor** [BitGo/BitGoJS#85]
I set up my access token as instructed in the documentation. I tried this 
````
var BitGo = require('bitgo');
var bitgo = new BitGo.BitGo({ accessToken: ACCESS_TOKEN }); 
bitgo.session({}, function(err,res) {
  console.dir(err);
  console.dir(res);
});
````
And this is what i get as response.
```
{ expectedHmac: '74497164697c9709b4c5e98a673738824cf71b908de173d896a2c80012677456',
     receivedHmac: undefined,
     hmacInput: '|/api/v1/client/constants|200|{"ttl":3600,"constants":{"maxFee":100000000,"maxFeeRate":10200,"minFeeRate":0,"minInstantFeeRate":-1000,"fallbackFeeRate":1020,"minOutputSize":2730,"defaultGasPrice":30000000000000,"bitgoEthAddress":"0x0f47ea803926926f299b7f1afc8460888d850f47","enableSegwit":true,"eth":{"tokens":[{"type":"terc","tokenContractAddress":"0x945ac907cf021a6bcd07852bb3b8c087051706a9","decimalPlaces":1},{"type":"tbst","tokenContractAddress":"0xe5cdf77835ca2095881dd0803a77e844c87483cd","decimalPlaces":0}]}}}',
     requestToken: 'My Access Token goes here',
     bitgoToken: 'My access token also goes here' },
  status: 511 }
```
```
at errFromResponse (/home/proctor/coinkudi_node/node_modules/bitgo/src/bitgo.js:83:15)
    at handleResponseError (/home/proctor/coinkudi_node/node_modules/bitgo/src/bitgo.js:100:11)
    at tryCatcher (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/proctor/coinkudi_node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
  status: 401,
  result: 
   { error: 'unauthorized',
     name: 'Unauthorized',
     requestId: 'cjc2k95u20pvjg9rscb0xod38' },
  invalidToken: true }


```
Can someone please point out what i did wrong.

**Comment by paparyku** [comment]
@ukor I have the same problem. Did you ever figure out how to fix this problem?

**Comment by ukor** [comment]
@paparyku Yes i did - I was using access token from production site bitgo.com while i was on test environment. If you are on test environment. get your access token from test.bitgo.com

**Comment by ingYanetEnnis** [comment]
Im having same error but Im sure that  I have Access Token from test.bitgo.com... but Im getting this response:
`GET https://test.bitgo.com/api/v1/user/session
Error: unauthorized
    at errFromResponse (webpack-internal:///./node_modules/bitgo/dist/src/bitgo.js:108:15)
    at handleResponseError (webpack-internal:///./node_modules/bitgo/dist/src/bitgo.js:123:15)
From previous event:
    at Request.req.then (webpack-internal:///./node_modules/bitgo/dist/src/bitgo.js:410:50)
    at Request.superagent.Request.result (webpack-internal:///./node_modules/bitgo/dist/src/bitgo.js:96:17)
    at BitGo.session (webpack-internal:///./node_modules/bitgo/dist/src/bitgo.js:1500:14)
    at Object.init (webpack-internal:///./src/plugins/utils.js:22:11)
    at VueComponent.created (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/views/Home.vue?vue&type=script&lang=js&:259:60)
`

**Comment by ukor** [comment]
@ingYanetEnnis

- Are you calling bitgo API from the browser?

- could you post a snippet of your request code?

**Comment by ingYanetEnnis** [comment]
@ukor thanks for answering, i'm trying to call v2
My code following the documentation
https://www.bitgo.com/api/v2/#section/Software-Development-Kit

accessToken I generated it on the web (User Settings/AccesToken) add my IP my ip address
 
    const accessToken = 'v2x9a450854e5d113a60cee2ca5bc94a2e6185ccb3bc2c16263f5f6ca5320e06095';
    const bitgo = new BitGoJS.BitGo({ env: 'test', accessToken: accessToken });
    const coin = bitgo.coin('tbtc');
    let walletId = '5e4bc00f497c9d350600ce67eca39ad2';
    coin.wallets().get({ id: walletId })
      .then(function(wallet) {
        console.log(wallet._wallet);
      });

**Comment by ukor** [comment]
Your  `accessToken` is different from the `Authorization: Bearer`

**Comment by ingYanetEnnis** [comment]
@ukor 
Exactly that's happening to me but I don't know the reason
that's how it is sending

**Comment by ukor** [comment]
Check that you are not setting it a new value any where?
