### ISSUE TITLE
Error: ccm: tag doesn't match

### ISSUE THREAD

**Issue by pavlodvornikov** [BitGo/BitGoJS#96]
Hello. 

I'm constantly getting this error while trying to send coins. Same error for btc wallet using BitGoExpress API v1.

Could you please help with this ? 

```
BitGo-Express running
Environment: prod
Base URI: http://localhost:3080
handle: /api/v2/eth/wallet/<wallet id>/sendcoins
error 500: (object_error) {"message":"ccm: tag doesn't match","status":400}
Error: (object_error) {"message":"ccm: tag doesn't match","status":400}
    at /opt/bitgo/src/clientRoutes.js:398:15
    at tryCatcher (/opt/bitgo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/bitgo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/bitgo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/bitgo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/bitgo/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/bitgo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/bitgo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/bitgo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
127.0.0.1 - local_express [31/Jan/2018:07:57:55 +0000] "POST /api/v2/eth/wallet/<wallet id>/sendcoins HTTP/1.1" 500 165 "-" "python-requests/2.5.1 CPython/3.6.4 Linux/4.13.0-1002-gcp"
```

**Comment by thomas4019** [comment]
Hi, this error usually happens when you're sending the wrong wallet password to the endpoint. Please check that you're using the correct password.
